version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee-management-system
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306" # Map MySQL port to the host
    volumes:
      - db_data:/var/lib/mysql # Persist MySQL data

volumes:
  db_data: